# Example on how to use Postgres (latest available version) with a Community edition of Bonita
services:
    # Uncomment those lines to mount a volume with your dumps
    #volumes:
    #  - ~/my/test/dumps:/opt/bonita/dump

  # In case you have built an Application, use instead as example:
  # my-application:
  #  image: my-application-[my built environment]:[my aplication's semantic version]
  bonita:
    # image: bonita:2024.2
    image: bdp_gprocesos-qualification:0.0.2
    ports:
      - "8085:8080"
    environment:
      - DB_VENDOR=postgres
      - DB_HOST=10.1.46.75
      - DB_PORT=5435
      - DB_NAME=bonita
      - DB_USER=bonita
      - DB_PASS=bpm
      - LANG=es_ES.UTF-8
      - LANGUAGE=es_ES:es
      - LC_ALL=es_ES.UTF-8
      - BIZ_DB_NAME=business_data
      - BIZ_DB_USER=business_data
      - BIZ_DB_PASS=bpm
    restart: on-failure:2    